First code review
hafiz1379/JS-capstone-project pull request #51
Opened 2023-06-02 20:28 UTC by tomasesquivelgc

## Development branch includes:

 - Items fetched from TV shows API are JS generated in the document.
 - Each show card includes a like button and a like counter, a comment button, and a reserve button.
 - comment and reserve buttons both generate popUp cards containing show information, API fetch elements, and an input area to submit your own comment/reservation.
 - comments and reservation information are also fetched from a different API (involvement API)
 - You can also find an item counter on the header.
 - Readme file with detailed information on how to run the project, a project description including a demonstration video with the team behind the project, and a live demo.
 - Jest tests for all counter functions (commentCounter, likeCounter and reserveCounter).

2023-06-02 21:58 UTC, ishimwezachee requested changes
Hi @tomasesquivelgc  and @hafiz1379  and @mdg0410 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
![image](https://www.ipem-market.com/wp-content/uploads/Image1.gif)

##  Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-02 21:58 UTC, ishimwezachee commented on src/index.html
> +    <div id="reserveCard"></div>
- [ ]  You comments, likes and reservation are functioning properly , but they look different from the provided mockup.  Make sure to use the icons for likes, and buttons for comments and Reservations. it will make your application more beautiful and professional. 
![image](https://github.com/hafiz1379/JS-capstone-project/assets/43877689/5464c78c-6462-4407-b796-0ed7f77abc07)

- [ ]  You should write Reserve as a full word, not cutting it for the best user experience.  Just write reserve in full word.

2023-06-02 21:58 UTC, ishimwezachee commented on src/index.html
> +    </nav>
- [ ]  Your navigation header is a little bit different from the provided mockup, please make sure that there is no such space provided as it is designed from the mockup . 
![image](https://github.com/hafiz1379/JS-capstone-project/assets/43877689/df62f5ed-5e9c-4a3e-8046-5b15e23c6698)

2023-06-02 21:58 UTC, ishimwezachee commented on src/index.html
> +    </footer>
- [ ]  Make sure that the provided footer is similar to the one provided from the design.  seemed like you've added something we don't have from the mockup, while it has to resemble it. 
![image](https://github.com/hafiz1379/JS-capstone-project/assets/43877689/4ab41a69-225a-43ec-af3f-d1098d67637d)

2023-06-02 21:58 UTC, ishimwezachee commented on src/modules/__test__/commentCounter.test.js
> +  expect(document.querySelector('.commentNumber').innerHTML).toBe(`Comments (${data.length})`);
- [ ]  Like you did in movies counter, You should cover all edges cases, think of the scenario in which there 0 items on the page ( where counter return zero)

2023-06-02 21:58 UTC, ishimwezachee commented on src/modules/__test__/counterReserve.test.js
> +});
- [ ]  Like you did in movies counter, You should cover all edges cases, think of the scenario in which there 0 items on the page ( where counter return zero)

2023-06-02 22:05 UTC, tomasesquivelgc commented on src/index.html
> +    <div id="reserveCard"></div>
Hello @ishimwezachee , would you mind if I ask for some clarification? The comment and reserve buttons do not present any icons on the mockup. I understand we should change the like button for a different icon but what did you mean by the comment and reserve buttons? to be clear, those 2 are in fact buttons, so I don't understand your correction.

2023-06-02 22:08 UTC, tomasesquivelgc commented on src/modules/__test__/commentCounter.test.js
> +  expect(document.querySelector('.commentNumber').innerHTML).toBe(`Comments (${data.length})`);
Hello @ishimwezachee   , me again. I was in charge of comments and it's testing. My second test for this function takes into account the possibility of data being empty, as you can see on my second test: 'commentCounter should update comment title if data is empty'. when that happens the comment counter updates to 0 as opposed to hardcoding 0 as a starting point. Would you mind expanding on your point or correcting me please? otherwise I don't really know what I'm supposed to do. thank you.

2023-06-02 22:35 UTC, tomasesquivelgc commented on src/index.html
> +    </nav>
@ishimwezachee  Would this be okay? 
![image](https://github.com/hafiz1379/JS-capstone-project/assets/117373513/0c1ddd9c-7a83-4f48-9345-1550f1f9b458)
The elements were shifted to the flex start to resemble the mockup.

2023-06-03 14:23 UTC, Whoistolu commented on src/index.html
> +    </footer>
- Well resolved team 👍🏽

2023-06-03 14:41 UTC, Whoistolu commented on src/modules/__test__/commentCounter.test.js
> +  expect(document.querySelector('.commentNumber').innerHTML).toBe(`Comments (${data.length})`);
- Well resolved 👍🏽

2023-06-03 14:43 UTC, Whoistolu commented on src/modules/__test__/counterReserve.test.js
> +});
- [ ] Well resolved 👍🏽

2023-06-03 14:47 UTC, Whoistolu commented on src/index.html
> +    <div id="reserveCard"></div>
- Well resolved 👍🏽 
- [ ] [OPTIONAL] You could make it `Reservations` and not `reservations` to enhance more professionalism 👍🏽

2023-06-03 14:48 UTC, Whoistolu approved these changes
### Hi Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 14:49 UTC, merged